/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/vinrsr_logo_3d.glb --transform 
Files: public/vinrsr_logo_3d.glb [253.11KB] > C:\Programming Projects\vinrsr-portfolio\vinrsr_logo_3d-transformed.glb [18.58KB] (93%)
*/

import React from 'react'
import { useGLTF, MeshTransmissionMaterial } from '@react-three/drei'

export function Model(props, scale=[2, .5, 2]) {
  const { nodes, materials } = useGLTF('/vinrsr_logo_3d-transformed.glb')
  const logoMesh = nodes.mesh_logo;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.mesh_logo.geometry}
        // material={nodes.mesh_logo.material}
        rotation={[Math.PI / 2, 0, 0]}
        scale={scale}
        position={[0, 0, 0]}
      >
        <meshStandardMaterial 
          color="#bebebe"  // The base color of the metal
          metalness={0}   // How metallic it is (0=non-metal, 1=full metal)
          roughness={0}   // How rough the surface is (0=mirror, 1=matte)
        />

        {/* <MeshTransmissionMaterial 
          transmission={1}
          thickness={0.5}
          roughness={0.1}
          color="#c0c0c0"
        /> */}
      </mesh>
    </group>
  )
}

useGLTF.preload('/vinrsr_logo_3d-transformed.glb')
